### ISSUE TITLE
Question of in game quest

### ISSUE THREAD

**Issue by NarMryy** [Wynd/mineminenomi#102]
I started play this mod for some time and i just found the swordman quest house so i do quest there.My question is did this mod have other quest except the swordman quest? If have so where can i find it?? Im really want to do some more Quest! Because the swordman Quest im stuck with the kill 20creature nearby moutain i do it but it not work.I find in any biome but didnt see other 
so i come to ask about this. thanks! sorry for bad english

**Comment by Wynd** [comment]
Right now no, those 4 quests are sort of a "demo" if you want, more quests will be added in the future as we go.
