### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by adrian200145** [Wynd/mineminenomi#103]
Im suggesting this from my ignorance on mod making but i think it would be cool if in the future you added mobs like sea kings, more marine ranks or more pirates and maybe marine bases. I know this is a lot what im demanding and i undestand if you wont do it, overall this is a great mod

**Comment by Wynd** [comment]
Generally speaking, that's what 0.6.0 will be all about, more things to do, including killing, raiding and all of those fun things, so don't worry :) soon:tm:
