### ISSUE TITLE
detail for the zoans

### ISSUE THREAD

**Issue by MXlordsMapone123** [Wynd/mineminenomi#119]
here are my suggestions for the zoans

-add effects like mod morph or similar to zoans

-add bite power to the carnivore zoans

-and also my four favorite anime zoans would like you to add them in an update focused on zoans

-inu inu no mi wolf mode,tori tori bird mode,inu inu jackal mode,neko neko leopard model

**Comment by MXlordsMapone123** [comment]
I forgot you can increase the size of the hybrid shape and complete the zou zou no mi

**Comment by FGpisces** [comment]
More zoans and zoan abilities will be added later, they're planned.
