### ISSUE TITLE
Haki suggestion

### ISSUE THREAD

**Issue by Geds1557** [Wynd/mineminenomi#123]
I like your mod, but I don't understand this Haki system. Like can you make that player will awake it while fighting(like if Player has lesser then 8-5 hp, than he might awake one type of Haki) or through Sensei(someone like Rayleigh, but he will give you quests or will require Beli) + I hope you will add something like Haki Progression. Like we will be able to get only 1st level of Ken or Buso through Sensei and other levels will be able only through fights(For example: on 1st Ken level you can see the only distance from foe then you can see auras, then who is your enemy, etc. Ofc your dodge chance will also increase). And about Hao haki, it will be cool if Player will have small chances to be born with it(at least 1/10)  and then he can accidentally awake it and will stun all near foes. I hope at least something will be added to the game. Thank you for your attention.

**Comment by jnd066** [comment]
Would be cool

**Comment by FGpisces** [comment]
Haki is a major aspect of the upcoming update, look forward to many improvements on it.
