### ISSUE TITLE
suggestion about releasing skills.

### ISSUE THREAD

**Issue by MrE66** [Wynd/mineminenomi#135]
something that I think the mod should have is a skill level system (both class and fruit), something I wanted to do is also put the anime bosses (crocodile, morgan, arlong etc), I know it's a lot But this is what I wanted to see in mod.

ps:
sorry my bad english, I'm using google translator because I don't understand english.

**Comment by FGpisces** [comment]
The classes will have something like a skill level system later, but not the devil fruit. We also plan to add more bosses soon.
