### ISSUE TITLE
Black Leg Style

### ISSUE THREAD

**Issue by BREEZEXPVP** [Wynd/mineminenomi#145]
**Add new combat style Black leg**

### abilities 

**Diable Jambe have to be a gear like Gear 2 or so , with it you get all the attacks with fire and more strength**

here is the list that could be in the black leg style

**Mouton Shot**
**Extra Hachis**
**Flambage Shot**
**Hell Memories**

**Sky Walk**

**Comment by FGpisces** [comment]
Black leg style is something that we will only add when we can get a "kicking" animation working for the player model, but we aren't focusing on that right now, so it'll have to wait.
