### ISSUE TITLE
Recipe Suggestion

### ISSUE THREAD

**Issue by LitaMasta360** [Wynd/mineminenomi#146]
Hi!
I dont know if you have the recipes for the mod, but I got some recipes that I like to show you...

![BKPN](https://user-images.githubusercontent.com/45587089/67247642-a0c9ea80-f427-11e9-9063-e38014f5604a.png)
![HYJB](https://user-images.githubusercontent.com/45587089/67247643-a0c9ea80-f427-11e9-94f3-9f19a45e7737.png)
![SDST](https://user-images.githubusercontent.com/45587089/67247644-a0c9ea80-f427-11e9-850a-08e03305f9c3.png)
![ZOROS SWORDS](https://user-images.githubusercontent.com/45587089/67247645-a0c9ea80-f427-11e9-90ad-2b782c078790.png)

**Comment by FGpisces** [comment]
Being nice recipes, we plan to add a completely different way to obtain these weapons, not by crafting.
