### ISSUE TITLE
Hito Hito No Mi

### ISSUE THREAD

**Issue by AlpacaFruit** [Wynd/mineminenomi#148]
Hi im a big fan of this mod
But its sad that the hito hito no mi (human fruit) has no use, could you please make that you can feed it to a animal to make you a pet or something.
Or mabye a rumble ball so that you turn to a giant after eating it or something like this because ist sad that this fruit is trash with no use. Because the fruit itself isnt that trash ist just trash for humans, for animals ist a Pretty cool ability.

I know its mabye hard to make and there are not much informations about but a Methode to generate smile fruits would also be realy cool. I mean like you Need to get the sad and then you can plant a apple with it and then there is a plant that gives a smile fruit but also with the chance that is trash, i think you know what i mean XD

Thanks for reading

**Comment by BREEZEXPVP** [comment]
this fruit is able to change your race if your a cyborg or fishman you get humain race if you eat it "good for servers" also you can't craft the mine mine no mi book now even if you die you don't get the book so its not trash its great for chaning races to get rokushiki powers

**Comment by FGpisces** [comment]
Just as said, it's basically only used as a race changer from fishman/cyborg to human, and we don't plan to make it usable in any other way right now.
We also don't plan to add SMILE fruits in the near future,since we first want to add most "normal" fruits.
