### ISSUE TITLE
[1.14]Kairoseki Items effect the non-devilfruit users with nausea

### ISSUE THREAD

**Issue by BREEZEXPVP** [Wynd/mineminenomi#150]
**the bug**
Kairoseki items effect the player with nausea without having a devil fruit

**To Reproduce**

1. give your self a sea stone item any one of them works
2. put it in your inventory 
3. make sure that you don't have any devil fruit
4. bug reproduced

**Expected behavior**
Should not effect the player  at all , should only effect devil fruit users

**Screenshots**
not a devil fruit user
![2019-12-14_22 29 42](https://user-images.githubusercontent.com/40163506/70854818-48f8ae80-1ec1-11ea-974a-1293f97d9304.png)

![2019-12-14_22 24 18](https://user-images.githubusercontent.com/40163506/70854787-e30c2700-1ec0-11ea-879d-7525618ba059.png)

**Additional context**
it works with 
Kairoseki item , Dense kairoseki , kairoseki block & bars , kairoseki ore , kairoseki bullet ,

**Comment by Wynd** [comment]
Big oopsie on my side :(

**Comment by Wynd** [comment]
Fixed
