### ISSUE TITLE
[1.14]Boxes not working 

### ISSUE THREAD

**Issue by BREEZEXPVP** [Wynd/mineminenomi#151]
**Describe the bug**
unboxing not working or the randomizer not giving the items.
wooden iron golden boxes all of them are effected

**To Reproduce**
1. Need keys & boxes w.i.g work with all of them
2. Righ click to unbox
3. See the reward, Nothing

**Expected behavior**
Should give a devil fruit after unboxing it & them ,

**Screenshots**
![2019-12-14_22 36 27](https://user-images.githubusercontent.com/40163506/70854971-8eb67680-1ec3-11ea-9471-996b94a09172.png)
![2019-12-14_22 37 09](https://user-images.githubusercontent.com/40163506/70854974-92e29400-1ec3-11ea-84b9-a7b94d346f6c.png)

**Additional context**
there rate to drop a devil fruit  should be at 70% or less

**Comment by FGpisces** [comment]
That somehow totally slipped testing, sorry, will be fixed really soon.

**Comment by Wynd** [comment]
Fixed
