### ISSUE TITLE
Mistery Note mission

### ISSUE THREAD

**Issue by freitasdlima** [Wynd/mineminenomi#157]
Hi, what i have to do to complete the mistery note mission of dojo sensei?

**Comment by Wynd** [comment]
It's a work in progress quest so I'm not sure if it works, it shouldn't even be there to begin with, but if I remember correctly you need to right click a librarian (white coated villager) with the note and then bring it back the sensei.

**Comment by freitasdlima** [comment]
Hey man, i just did what you say and its works,thanks
