### ISSUE TITLE
FIGTHER CLASS AND NITTORYU

### ISSUE THREAD

**Issue by freitasdlima** [Wynd/mineminenomi#159]
HI, i have two suggestions, the first is a new class named figther, many characters of one piece figth without a weapon and i think this could be in the game in a class with abilitys to figth without weapon like the fishman abilitys does, i know we already have the cp9 abilitys but what i am suggesting are abilitys you can use in the begin of game like sword abilitys

The second one was a new style for swordmanship with two swords, this could be maked like a class promotion

**Comment by FGpisces** [comment]
The fighter class is a highly suggested feature and will be implemented later. The 2- and 3-sword style are also planned as an upgrade to the swordsman class.
