### ISSUE TITLE
[Suggestion] Mihawk's boat and dojo sensei/ fighting style rework

### ISSUE THREAD

**Issue by jnd066** [Wynd/mineminenomi#162]
At this moment the dojo's sensei only teaches you about the swordman figthing style, and even if you chose it, he actualy isn't necessary to nothing i think that would be better if the player choose the figthing style by asking to the specific figthing style sensei (would be a sensei for each figthing style) 
, and the player would need to finish the first quest to become a swordman, sniper, art of weather and etc..., and would be niciest if each one fighting style has its own variations  example a swordman would choose between use 1,  2 or 3 swords.

And also a little thing that would make the mod a lot better is mihawk's boat 
![image](https://user-images.githubusercontent.com/56661453/72213110-e5659f00-34c7-11ea-9fcd-2e7bca8e3038.png) because it helps a df users

sorry if i made some a mistakes in english, and Thank you for paying atenttion

**Comment by FGpisces** [comment]
The reason the swordsman quest is pretty much useless at the moment is because it's a test-only feature, you'll have to unlock the abilities through the quests in the future, you won't get them at the start. And more sword styles and boats are also planned for future releases.
