### ISSUE TITLE
Gameplay suggestion and thoughts

### ISSUE THREAD

**Issue by Zulster** [Wynd/mineminenomi#168]
`I suggest that you guys should add more enemies and things to do. Currently the game is fantastic, don’t get me wrong, but it is missing some One Piece aspects. For Ex: There are boats, but they’re randomly generated structured, it would be awesome if we could make a boat through building, and with certain things, it can move, and the same with the other npc boats. There could also be more enemies like maybe a Crocodile boss, and Blackbeard boss, and that Wano Kingdom samurai Zoro fought in Thriller Bark Arc, and make it so the Shisui can actually be dropped (and the other bosses can drop things to like for ex, crocodile drops the hook and blackbeard can drop his coat) - And I’m not sure if this is in the game, but incase its not, add Haoshuko Haki but make it so its a 1 in like 5K or so chance to get. My reason for suggesting these Ideas is because although the game is great, I feel like the fruits are being more prioritized because fruits are amazing, I agree as well, but so is the gameplay and things we can do with these awesome well made fruits. All we can really at the moment is to eat a fruit, explore, raid a ship that doesn’t move from the front by either mining or actually going in, and thats really it at the moment. There’s also navy bases and such but there is more to One Piece. I hope I’m not asking for to much lol, just wanted to suggest this because I wanted to be honest and give the ideas along the way lol. Great mod though nonetheless, keep up the great work!`

**Comment by FGpisces** [comment]
Hi,
we don't plan to add anything that is already present in other mods, like building your own ship out of blocks, but we do plan on adding bosses and more enemies, coming straight next update.
Also, Hao haki is already modified that not everyone gets it, you can check the way it works in the config, or on our website in the changelog.
And we would love to add a lot more aspects, but this isn't the only mod we're developing, and there aren't a lot of us, having another coder or two would really speed things up, but we work with what we have.
Thanks for the support.
