### ISSUE TITLE
Revive Revive Fruit & Mero Mero fruit permanent screen blurs

### ISSUE THREAD

**Issue by Kadamitas** [Wynd/mineminenomi#170]
**Describe the bug**
After someone used their abilities on you till death you gain permanent screen colorings, gray for mero mero, blue for revive fruit

**To Reproduce**
1. Get hit by pistol kiss and all other abilities
2. die
3. can't craft anything because it permanently blinds you

**Expected behavior**
it should go away, I thought that if I got hit with another ability that causes the gray screen it'd go away but it didn't

**Screenshots**
![image](https://user-images.githubusercontent.com/29363268/77243127-6f229e80-6bd4-11ea-87d9-2adc6b492d26.png)
![image](https://user-images.githubusercontent.com/29363268/77243135-7f3a7e00-6bd4-11ea-82a3-8152dbed72c1.png)

**Additional context**

**Comment by Kadamitas** [comment]
Specifically it'd be something like
xyz.pixelatedw.MineMineNoMi3.abilities.effects.DFEffectMeroPetrification

**Comment by FGpisces** [comment]
Hi, we know about the glitch that's causing this, which is fixed in the 1.14 version of this mod. To fix it as it is, removing Optifine should also work.
