### ISSUE TITLE
Question about getting haki

### ISSUE THREAD

**Issue by Dinoknower** [Wynd/mineminenomi#172]
i have a question about getting haki^^, the problem is i make the command for doriki to have exact 10000 but i dont get or unlock the  observitation or hardening haki anyway^^,

**Comment by FGpisces** [comment]
As of version 0.6.0, you have to get haki by other means, which are specific to the type, having doriki isn't enough (though you still need like a minimal amount of around 2000). E.g. beat mobs with a sword to get Imbuing haki, with a fist to get hardening, etc.
