### ISSUE TITLE
Ice related movies glitching to blue screen

### ISSUE THREAD

**Issue by CeeMoney** [Wynd/mineminenomi#175]
I play a server on 1.7.10, when any ice related moves are used on players sometimes glitches them , when they try to type or open inventory or even a chest it glitches a light blue screen. Is it possible you fix this please because the yomi yomi was banned and I since we’re moving island by island which is cool, punk hazard will come out soon and I really want the yuki yuki and I know someone who really wants the hie hie can you please fix this small bug? It’s hurting smally but surely

**Comment by Wynd** [comment]
Its already fixed in the 1.14.4 version, the 1.7 is no longer supported and as such this will never get fixed.
