### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Bigoof3** [Wynd/mineminenomi#176]
are you guys going to make more devil fruit or are you guys going stick with 43

**Comment by FGpisces** [comment]
Of course we're going to add more DFs, we'd pretty much like to add all of them as the time goes on, but right now we think there are enough so that we can concentrate on other gameplay things.

**Comment by Bigoof3** [comment]
have you added Inugami Guren to Akainus devil fruit moveset

**Comment by FGpisces** [comment]
No, not yet, but we plan to later.

**Comment by Bigoof3** [comment]
how's your jojo modpack looking

**Comment by FGpisces** [comment]
If you mean mod, then you can check it out through our website or our discord (link on the website)
https://pixelatedw.xyz

**Comment by Bigoof3** [comment]
What other 5 stands are you guys planning to put in your mod

**Comment by FGpisces** [comment]
We have no idea yet since we're busy working on Mine Mine no Mi right now. Join our discord for more questions.
