### ISSUE TITLE
1.7.10 build.gradle not working

### ISSUE THREAD

**Issue by D-Captain-WAIS** [Wynd/mineminenomi#177]
.\gradlew Eclipse runs an error

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Workspace\mineminenomi-1.7.10\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'mineminenomi-1.7.10'.
> Cannot get property 'branch' on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.688 secs

**Comment by Wynd** [comment]
Problem occurs because you've downloaded the project instead of using git clone, so it cannot find the .git folder and repo details.
