### ISSUE TITLE
Cant complete quest "Feel the wind" mc 1.7.10

### ISSUE THREAD

**Issue by damaxian** [Wynd/mineminenomi#182]
Quest say that you need to kill mobs in mountain biome, but in minecraft 1.7.10 doesn't have that biome, only extreme hills and frozen mountains.

1. Go to dodze as swordman
2. Complete two quests
3. Take third quest

**Comment by Wynd** [comment]
Yes...extreme hills or extreme hills + count as "mountains"

**Comment by damaxian** [comment]
but progress doesn't count
