### ISSUE TITLE
Suggestion: Fruit Respawns

### ISSUE THREAD

**Issue by CalebGitBritannia** [Wynd/mineminenomi#42]
So I am getting more confident after transferring from spigot to forge, one idea I had was to enable fruit re spawns

Essential when a player dies, if there is an apple on the ground within 100 blocks it turns into the devil fruit (also maybe in a players inventory?)

Just want to hear feedback on this idea and check noone is already developing it.

This may take a while as I am still getting used to the forge API though, this is more of a learning experience for me.

**Comment by MXlordsMapone123** [comment]
in the next update you can increase the size of the swords? they are very small

**Comment by FGpisces** [comment]
Yes, it's already planned to make swords bigger in-hand.
