### ISSUE TITLE
Some ideas for the mod

### ISSUE THREAD

**Issue by DRtiempo** [Wynd/mineminenomi#69]
I like the mod and thanks for continuing to add new things, they do a great job. These are some ideas that occurred to me while playing the mod

- One is that you can generate a block / item depending on the fruit. This occurred to me because in the anime / manga many characters with DF, have the power to create an element, as aokiji can create ice or crocodile can create sand, but in the mod only shows the attacks and not what in itself does the DF For example, that the hie hie no mi has a capacity that adds ice to your inventory or that directly places a block of ice where you right click, as well as that the ito ito no mi has an ability that gives you threads, although it would only be in some fruits, the Kage kage no mi could not use this ability because it does not generate shadows, it only controls them.

- For the kage kage no mi you can add the kakumei Kage, in the anime / manga says that this attack causes that instead of the shadow adapting to the shape of the body, the body adapts to the shadow, so I thought I could do that in this mod this attack could alter the body of the owner, how to make you giant, increasing your strength but losing speed, or also could only enlarge the hands to make very strong hits, or also to increase the hit range of the character, making understand that the player stretched his arms with this power.

- Something also related to the kage kage no mi, having the ability to control the doppelman, could be something like shift + ability of doppelman, if this is done the doppelman is invoked and you control it, besides that while you control the doppelman your real body stays in a place and receive damage, and that to stop controlling the doppelman you must press shift, you go back to your real body and the doppelman stays in the place where you left it, this would also serve to use the kagemusha and exchange places with the doppelman

- They should add the hito hito no mi: model daibutsu, with which to transform into buddha, you have a great strength and endurance, but less speed, also possess an ability that if you hit an enemy, causes an explosion which you can charge to make it more powerful

- They should add islands of the sky, which appear randomly around the world floating, in which there can be enemies using dials as weapons, and also chests containing treasures and dials

- You can also make some skills of the DFs unlock as you have more douriki, for example the gomu gomu no mi, in the current version when you eat this fruit you have the gomu gomu no pistol, bazooka, gatling, rocket, gear 2, gear 3 and gear 4, you could make at first you only have the gomu gomu no pistol, and that, for example, when you have 100 douriki you unlock the next ability, and so with all the other DFs

- Another thing would be that the kairoseki appear in the sea, because this is a mineral from the sea, if this is not an improvement but it would be a detail that would add more similar to what is the world of one piece.

- Let bounty hunters appear, which will try to kill you, besides that the greater your reward the greater your strength will be.

- Add marine kings to the mod, this will make going by the sea and go for boats is more dangerous, and will add more difficulty trying to get DFs.

- They could put okama in the character editor, and if they choose this, they can learn to use the okama kenpo and the newkama kenpo, using techniques from bon clay and ivankov

**Comment by AdmiralSakazuki** [comment]
yeah  I also agree with you on the thing of unlocking moves with doriki or with a skill system that the more u use a df move u get skill points in that DF and that way you unlock new moves like a skill bar like on the roblox one piece games

**Comment by FGpisces** [comment]
Hi, thanks for the suggestion, I'll try to answer to each of them in order.

- For generating block, only those attacks generate blocks that need them, and I don't see a point adding the blocks directly to your inventory.

- Changing the player model is hard, but we already have a plan for Kage Kakumei and also some other Kage attacks that will hopefully look close to the anime.

- Like said above, we reworked some Kage attacks, Doppelman as well, with a new and improved AI.

- We'll add the DF, just not in the near future. We already have planned what zoans we're gonna make, cause they take a lot of time to do, but don't worry, we'll add the Buddha eventually.

- Nice idea, we'll try to add more generated structures and things like this in future updates.

- We won't be making a leveling system for DFs, and they won't be affected by Doriki. We think the DFs should be completely unrelated to Doriki and they shouldn't have to be leveled up.

- It already sawns like every other ore, but we could make it more common in oceans.

- Yes we're already planning such "scenarios" that will happen around the player.

- Sea kings currently don't have a model, or texture, and the old versions of them had no AI, so they'll take a lot of work to add.

- We'll add more races and fighting styles once we complete the current ones.

I hope I answered to all your suggestions accordingly. Thanks for your suggestions!
