### ISSUE TITLE
Some questions about 4th gear

### ISSUE THREAD

**Issue by SaoPig2333** [Wynd/mineminenomi#76]
Hello, author, I would like to put forward some suggestions on 4th gear. In animation, 4th gear is a very strong mode, and it makes the characters bigger. I think, can it be the same in mod as in animation? The 4 - file effect of version 0.4 is too little. I hope to be stronger and add some models. Thank the author.

**Comment by BREEZEXPVP** [comment]
**Yeah it will be cool , but you need to know that they have to make a model like the zoans and mby take more time to retexture / make the model with all the attacks or some of them , Snake Man then new form too**
