### ISSUE TITLE
suggestion about belly and another

### ISSUE THREAD

**Issue by Katakurikun** [Wynd/mineminenomi#90]
Good afternoon!

Belly doesnt have the function right? so why dont you make the function of it. 
You could buy many clothes or weapon with that belly. you could buy many foods with the belly
and could you make the others sword please.

also, could you add skill for zushi zushi no mi like many meteors falling
Thanks.

**Comment by Wynd** [comment]
For belly functionality we have a few things planned...not sure when they will be implemented but we'll see

For zushi zushi no mi we have to consider stability and lag, I mean with 1 meteorite is has a bit of lag when it hits the ground on lower end PCs so...I don't know we'll see if I can find a better way to add them
